Initial commit
metglobal-compass/microservice-maintenance pull request #1
Opened 2021-01-26 15:24 UTC by EmreKp

Bu pr'da iyileştirmeler olacak, ancak aciliyet durumunda buradan release alınabilir.

2021-01-27 11:32 UTC, EmreKp commented
repository ismini tekrardan değiştiremedim, sen halledebilir misin @goksagun abi?

2021-02-01 13:10 UTC, MehGokalp commented on README.md
> +   "success": true,
bunun yerine http kodları ile kullanıcıya bilgi vermenin daha doğru olacağını düşünüyorum

2021-02-01 13:22 UTC, EmreKp commented on README.md
> +   "success": true,
esasen success koymamın sebebi maintenance'daki true/false değeri ile karışıklık olmaması açısından, aslında direkt olarak boş response (204) da dönülebilir, ancak kontrol bakımından maintenance bilgisinin de verilmesi taraftarıyım

2021-02-02 12:31 UTC, goksagun commented on pom.xml
> +  <description>Microservice maintenance project written in Spring Boot</description>
Microservice ibarelerini kaldıralım

2021-02-02 12:31 UTC, goksagun commented on src/main/java/com/compass/maintenance/filter/MaintenanceFilter.java
> +      throw new RuntimeException("Server is under maintenance.");
503 (HTTP Status Code) mü dönüyor?

2021-02-02 12:31 UTC, goksagun commented on src/main/java/com/compass/maintenance/model/MaintenanceResponse.java
> +  private boolean isMaintenance;
`isMaintenance` yerine `message` olmalı ve aşağıdaki şekilde tanımlanmalılar;
```
    ERROR_MESSAGE = 'There is an error please try again.';
    SERVER_IS_ALREADY_LOCKED_MESSAGE = 'Server is already locking.';
    SERVER_IS_UNDER_MAINTENANCE_MESSAGE = 'Server is under maintenance.';
    SERVER_IS_ALREADY_ONLINE_MESSAGE = 'Server is already online.';
    SERVER_IS_ONLINE_MESSAGE = 'Server is online.';
```

2021-02-02 12:31 UTC, goksagun commented on src/main/java/com/compass/maintenance/service/MaintenanceService.java
> +    redisTemplate.opsForValue().set(projectName + ":maintenance", maintenanceMode.toString());
keyspace şu şekilde olmalı `maintenance.expires` ve GTM [rfc7231](https://tools.ietf.org/html/rfc7231#section-7.1.1.2) standardında `Tue, 15 Nov 1994 08:12:31 GMT` gibi olmalı.

2021-02-02 12:31 UTC, goksagun commented on src/main/java/com/compass/maintenance/filter/MaintenanceFilter.java
> +  public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain)
header da retry bilgisi olmalı header name `Retry-After` value `Tue, 02 Feb 2021 13:14:48 GMT`

2021-02-02 12:31 UTC, goksagun commented on src/main/java/com/compass/maintenance/config/BeanConfig.java
> +
default bir ttl olmalı


```
@Value("${maintenance.ttl:3600}")
private Integer ttl;
```

2021-02-03 09:14 UTC, EmreKp commented on README.md
> +   "success": true,
response yapısı api'deki standarda uygun olarak değiştirildi.

2021-02-03 09:59 UTC, EmreKp commented on src/main/java/com/compass/maintenance/filter/MaintenanceFilter.java
> +  public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain)
eklendi.

2021-02-03 10:30 UTC, EmreKp commented on src/main/java/com/compass/maintenance/config/BeanConfig.java
> +
eklendi.

2021-02-03 10:44 UTC, EmreKp commented on src/main/java/com/compass/maintenance/service/MaintenanceService.java
> +    redisTemplate.opsForValue().set(projectName + ":maintenance", maintenanceMode.toString());
keyspace düzeltildi.

2021-02-03 10:44 UTC, EmreKp commented on src/main/java/com/compass/maintenance/model/MaintenanceResponse.java
> +  private boolean isMaintenance;
👍

2021-02-10 10:28 UTC, goksagun commented on README.md
> +If request is successful, we should get this response (e.g. if maintenance became off):
Header bilgilerini de ekler misin? Header'da ne döndüğünü de görelim dökümanda ona göre entegrasyon yapacağız.

2021-02-11 08:11 UTC, EmreKp commented on README.md
> +If request is successful, we should get this response (e.g. if maintenance became off):
eklendi.

2021-02-17 20:17 UTC, goksagun requested changes
Testleri de ekler misin?

2021-03-09 08:09 UTC, goksagun approved these changes

2021-03-09 08:10 UTC, merged